# permissions for end users to view mustgathers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mustgather-viewer-role
rules:
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - mustgathers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - mustgathers/status
  verbs:
  - get
